[package]
name = "bipa"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
reqwest = "0.12.8"
serde = "1.0.210"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
